name: CI/CD Pipeline - Guptha's E-Commerce Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: |
        docker build -t guptha/ecommerce-frontend:latest .

    - name: Push Docker Image to Docker Hub
      run: |
        docker push guptha/ecommerce-frontend:latest

    - name: Run Docker Container
      run: |
        docker run -d -p 8080:80 --name ci-cd-webapp guptha/ecommerce-frontend:latest

    - name: Wait for the container to start
      run: |
        sleep 10  # Wait for 10 seconds to ensure that the container is up

    - name: Test Website Homepage
      run: |
        curl --fail http://localhost:8080 || exit 1
