name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger CI/CD on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on PRs to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/your-app-name:latest

    - name: Deploy to your environment (e.g., VM, Kubernetes)
      run: |
        # Deploy your Docker image here (local VM or Minikube)
        # Example (Docker run command for local VM):
        docker run -d -p 80:80 ${{ secrets.DOCKER_USERNAME }}/your-app-name:latest
